# Generated by Django 5.0 on 2024-07-08 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_frequentlyaskeduestion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FrequentlyAskeduestion',
            new_name='FrequentlyAskedQuestion',
        ),
    ]
