# Generated by Django 5.0 on 2024-07-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
