# Generated by Django 5.0 on 2024-07-11 12:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='company_name',
            field=models.CharField(default='Company', max_length=255),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='user_job_title',
            field=models.CharField(max_length=50),
        ),
    ]
